#!/bin/bash -e
#
# commit-current-partition - make current partition boot/root set the default
#
# Run this after a successful tryboot test to make the current partition permanent
#
# Requires: mount, blkid
#
# Version: v0.1
# Author: Josh Schmelzle
# License: BSD-3

echo_status() {
    echo -e "\e[1;34m>>> $1\e[0m"
}

echo_debug() {
    echo -e "\e[1;36mDEBUG: $1\e[0m"
}

echo_warning() {
    echo -e "\e[1;31mWARNING: $1\e[0m"
}

echo_error() {
    echo -e "\e[1;31mERROR: $1\e[0m"
    exit 1
}

if [ "$(id -u)" -ne 0 ]; then
    echo_error "Need elevated permissions ... run as root (sudo) ..."
fi

echo_status "Starting partition commit process ..."

CURRENT_ROOT=$(findmnt -n -o SOURCE /)
CURRENT_BOOT=$(findmnt -n -o SOURCE /boot)
echo_debug "Current root: $CURRENT_ROOT"
echo_debug "Current boot: $CURRENT_BOOT"

if [[ $CURRENT_ROOT == *"p5"* && $CURRENT_BOOT == *"p1"* ]]; then
    echo_debug "Currently on partition set A (boot p1, root p5)"
    CURRENT_SET="A"
    CURRENT_BOOT_NUM=1
    ALT_BOOT_NUM=2
    BOOT1_DEV=$CURRENT_BOOT
elif [[ $CURRENT_ROOT == *"p6"* && $CURRENT_BOOT == *"p2"* ]]; then
    echo_debug "Currently on partition set B (boot p2, root p6)"
    CURRENT_SET="B"
    CURRENT_BOOT_NUM=2
    ALT_BOOT_NUM=1
    BOOT1_DEV="${CURRENT_BOOT/p2/p1}"
else
    echo_warning "Detected mixed partition usage!"
    echo_debug "Root from: $CURRENT_ROOT"
    echo_debug "Boot from: $CURRENT_BOOT"

    if [[ $CURRENT_BOOT == *"p1"* ]]; then
        CURRENT_BOOT_NUM=1
        ALT_BOOT_NUM=2
        BOOT1_DEV=$CURRENT_BOOT
        echo_debug "Using boot partition 1"
    elif [[ $CURRENT_BOOT == *"p2"* ]]; then
        CURRENT_BOOT_NUM=2
        ALT_BOOT_NUM=1
        BOOT1_DEV="${CURRENT_BOOT/p2/p1}"
        echo_debug "Using boot partition 2"
    else
        echo_error "Unable to determine boot partition number"
    fi
fi

echo_status "Committing to current partition set ..."

# Always update autoboot.txt on partition 1 (boot A)
echo_debug "Mounting boot partition 1 (the default boot partition) ..."
BOOT1_MNT=$(mktemp -d)
mount "$BOOT1_DEV" "$BOOT1_MNT"

echo_debug "Updating autoboot.txt on boot partition 1 to point to boot partition $CURRENT_BOOT_NUM ..."
cat > "$BOOT1_MNT/autoboot.txt" << EOF
[all]
boot_partition=$CURRENT_BOOT_NUM
tryboot_a_b=1
EOF

echo_debug "New autoboot.txt content on boot partition 1:"
cat "$BOOT1_MNT/autoboot.txt" | sed 's/^/    /'

umount "$BOOT1_MNT"
rmdir "$BOOT1_MNT"

echo_status "Partition commit complete"
echo_debug "Partition set $CURRENT_SET is now the default boot option"
echo_debug "This configuration will persist across all future reboots and power cycles"
echo