# Increase history limit for more scrollback
set -g history-limit 10000

# Start window numbering at 1
set -g base-index 1

# Start pane numbering at 1
setw -g pane-base-index 1

# Renumber windows when one is closed
set -g renumber-windows on

# Enable easy config reload
bind R source-file ~/.tmux.conf \; display "Config reloaded ..."
bind m set -g mouse \; display "Mouse mode #{?mouse,ON,OFF}"

# Right status bar
set -g status-right-length 60
set -g status-right '#{?window_zoomed_flag,[Z],} #(ip -br addr show | grep -v "^lo" | grep UP | awk "{print \$1\":\"\$3}" | head -n1) | #H | %H:%M '

# Left status bar
set -g status-left-length 30
set -g status-left "[#S]#{?client_prefix, #[bg=red]PREFIX#[default],}#{?#{==:#{client_key_table},RESIZE}, #[bg=red]RESIZE#[default],} "

# Colors
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"

# Set status bar colors to dark gray with orange highlights
set -g status-style fg=white,bg=colour234
set -g message-style fg=white,bold,bg=colour234

# If we're root
if-shell '[ $(id -u) -eq 0 ]' \
  'set -g status-bg colour88; set -g status-left "#[bg=colour88,fg=colour231,bold] ROOT #[fg=colour231,bg=colour88][#S]#{?client_prefix, PREFIX,}#{?#{==:#{client_key_table},RESIZE}, #[bg=red]RESIZE#[default],} "'


# Update window status colors
setw -g window-status-style fg=colour244,bg=colour234
setw -g window-status-current-style fg=white,bold,bg=colour27

# Window activity monitoring
setw -g monitor-activity on
set -g visual-activity on

# Enable mouse mode
set -g mouse on
set -g repeat-time 500

# Add shortcut for synchronizing panes (useful for running same commands on multiple servers)
bind S setw synchronize-panes

# Update pane borders to match theme
set -g pane-border-style fg=colour237
set -g pane-active-border-style fg=colour208,bold

# Display a visual indicator when a pane is in synchronized mode
setw -g window-status-current-format '#{?pane_synchronized,#[bg=red],}#I:#W#{?pane_synchronized,#[default],}'

# Add quick session switching
bind-key C-s choose-tree -Zs
bind-key S command-prompt "switch-client -t %%"

# Create a persistent resize mode with explicit RESIZE key table
bind r switch-client -T RESIZE

# Define resize mode bindings with explicit returning to normal  mode
bind -T RESIZE h resize-pane -L 5 \; switch-client -T RESIZE
bind -T RESIZE j resize-pane -D 5 \; switch-client -T RESIZE
bind -T RESIZE k resize-pane -U 5 \; switch-client -T RESIZE
bind -T RESIZE l resize-pane -R 5 \; switch-client -T RESIZE
bind -T RESIZE Escape switch-client -T root