#!/bin/bash -e

mkdir -p "${ROOTFS_DIR}/boot/firmware"

if ! [ -L "${ROOTFS_DIR}/boot/overlays" ]; then
	ln -s firmware/overlays "${ROOTFS_DIR}/boot/overlays"
fi

install -m 644 files/config.txt "${ROOTFS_DIR}/boot/firmware/"

# WLAN Pi Pro custom overlay (bq27546 battery fuel gauge). Referenced by
# config.txt (dtoverlay=battery_gauge) and required for Pro platform detection.
mkdir -p "${ROOTFS_DIR}/boot/firmware/overlays"
install -m 644 files/battery_gauge.dtbo "${ROOTFS_DIR}/boot/firmware/overlays/"

for file in cmdline.txt config.txt; do
	printf "DO NOT EDIT THIS FILE\n\nThe file you are looking for has moved to %s\n" "/boot/firmware/${file}" > "${ROOTFS_DIR}/boot/${file}"
done
